# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78e6d4a46e1f843316f717bacc229534eda4c0c626d6488556120f87d577dbc1f6ae5a64270a168d40466e0cd0896fae27b0f7d79ca805b1cdd8a4140157194e

test:
  secret_key_base: b1f05b2f37ccf1386459d0f547045d978707d9eac8436dce0640e7b3ec0a6f11b31ea37d6883b59b2c07d967c7bee9d155fe821f8a6116d2b9f2c96ed52b89e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
