# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55093ec9d88492487f5d3f55ab0c50a61adb129890ad3e7bce2f5245c8bec0d9621dd2e4db8dd86c626fff1c9485d1d5c3573b8fdb3deb492dc4832be5aeac05

test:
  secret_key_base: e9c400d9c4aa7decd840d0a34b19829c0dfad3b8f668cc4126db935860df907b465f986820e710934b61021dd5e0b3f82343425cac78f38be2d9de286481ef68

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
